[font]
normal = { family = "CodeNewRoman Nerd Font", style = "Regular" }
bold = { family = "CodeNewRoman Nerd Font", style = "Bold" }
italic = { family = "CodeNewRoman Nerd Font", style = "Italic" }
bold_italic = { family = "CodeNewRoman Nerd Font", style = "BoldItalic" }
size = 8.0

[window]
opacity = 0.75
